name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pre-commit
      - name: Lint
        run: |
          pre-commit run --all-files --show-diff-on-failure
        env:
          PRE_COMMIT_COLOR: always
